// SPDX-FileCopyrightText: 2024-present Proxima Fusion GmbH
// <info@proximafusion.com>
//
// SPDX-License-Identifier: MIT
#ifndef VMECPP_VMEC_OUTPUT_QUANTITIES_TEST_HELPERS_H_
#define VMECPP_VMEC_OUTPUT_QUANTITIES_TEST_HELPERS_H_

#include "gtest/gtest.h"
#include "vmecpp/vmec/output_quantities/output_quantities.h"

// check for equality of two `WOutFileContents` using the Google test framework
inline void CheckWOutEquality(const vmecpp::WOutFileContents& wout1,
                              const vmecpp::WOutFileContents& wout2) {
  EXPECT_EQ(wout1.version_, wout2.version_);
  EXPECT_EQ(wout1.signgs, wout2.signgs);
  EXPECT_EQ(wout1.gamma, wout2.gamma);
  EXPECT_EQ(wout1.pcurr_type, wout2.pcurr_type);
  EXPECT_EQ(wout1.pmass_type, wout2.pmass_type);
  EXPECT_EQ(wout1.piota_type, wout2.piota_type);
  EXPECT_EQ(wout1.am, wout2.am);
  EXPECT_EQ(wout1.ac, wout2.ac);
  EXPECT_EQ(wout1.ai, wout2.ai);
  EXPECT_EQ(wout1.am_aux_s, wout2.am_aux_s);
  EXPECT_EQ(wout1.am_aux_f, wout2.am_aux_f);
  EXPECT_EQ(wout1.ac_aux_s, wout2.ac_aux_s);
  EXPECT_EQ(wout1.ac_aux_f, wout2.ac_aux_f);
  EXPECT_EQ(wout1.ai_aux_s, wout2.ai_aux_s);
  EXPECT_EQ(wout1.ai_aux_f, wout2.ai_aux_f);
  EXPECT_EQ(wout1.nfp, wout2.nfp);
  EXPECT_EQ(wout1.mpol, wout2.mpol);
  EXPECT_EQ(wout1.ntor, wout2.ntor);
  EXPECT_EQ(wout1.lasym, wout2.lasym);
  EXPECT_EQ(wout1.ns, wout2.ns);
  EXPECT_EQ(wout1.ftolv, wout2.ftolv);
  EXPECT_EQ(wout1.niter, wout2.niter);
  EXPECT_EQ(wout1.lfreeb, wout2.lfreeb);
  EXPECT_EQ(wout1.mgrid_file, wout2.mgrid_file);
  EXPECT_EQ(wout1.extcur, wout2.extcur);
  EXPECT_EQ(wout1.mgrid_mode, wout2.mgrid_mode);
  EXPECT_EQ(wout1.wb, wout2.wb);
  EXPECT_EQ(wout1.wp, wout2.wp);
  EXPECT_EQ(wout1.rmax_surf, wout2.rmax_surf);
  EXPECT_EQ(wout1.rmin_surf, wout2.rmin_surf);
  EXPECT_EQ(wout1.zmax_surf, wout2.zmax_surf);
  EXPECT_EQ(wout1.mnmax, wout2.mnmax);
  EXPECT_EQ(wout1.mnmax_nyq, wout2.mnmax_nyq);
  EXPECT_EQ(wout1.ier_flag, wout2.ier_flag);
  EXPECT_EQ(wout1.aspect, wout2.aspect);
  EXPECT_EQ(wout1.betatotal, wout2.betatotal);
  EXPECT_EQ(wout1.betapol, wout2.betapol);
  EXPECT_EQ(wout1.betator, wout2.betator);
  EXPECT_EQ(wout1.betaxis, wout2.betaxis);
  EXPECT_EQ(wout1.b0, wout2.b0);
  EXPECT_EQ(wout1.rbtor0, wout2.rbtor0);
  EXPECT_EQ(wout1.rbtor, wout2.rbtor);
  EXPECT_EQ(wout1.IonLarmor, wout2.IonLarmor);
  EXPECT_EQ(wout1.volavgB, wout2.volavgB);
  EXPECT_EQ(wout1.ctor, wout2.ctor);
  EXPECT_EQ(wout1.Aminor_p, wout2.Aminor_p);
  EXPECT_EQ(wout1.Rmajor_p, wout2.Rmajor_p);
  EXPECT_EQ(wout1.volume, wout2.volume);
  EXPECT_EQ(wout1.fsqr, wout2.fsqr);
  EXPECT_EQ(wout1.fsqz, wout2.fsqz);
  EXPECT_EQ(wout1.fsql, wout2.fsql);
  EXPECT_EQ(wout1.iotaf, wout2.iotaf);
  EXPECT_EQ(wout1.q_factor, wout2.q_factor);
  EXPECT_EQ(wout1.presf, wout2.presf);
  EXPECT_EQ(wout1.phi, wout2.phi);
  EXPECT_EQ(wout1.phipf, wout2.phipf);
  EXPECT_EQ(wout1.chi, wout2.chi);
  EXPECT_EQ(wout1.chipf, wout2.chipf);
  EXPECT_EQ(wout1.jcuru, wout2.jcuru);
  EXPECT_EQ(wout1.jcurv, wout2.jcurv);
  EXPECT_EQ(wout1.iotas, wout2.iotas);
  EXPECT_EQ(wout1.mass, wout2.mass);
  EXPECT_EQ(wout1.pres, wout2.pres);
  EXPECT_EQ(wout1.beta_vol, wout2.beta_vol);
  EXPECT_EQ(wout1.buco, wout2.buco);
  EXPECT_EQ(wout1.bvco, wout2.bvco);
  EXPECT_EQ(wout1.vp, wout2.vp);
  EXPECT_EQ(wout1.specw, wout2.specw);
  EXPECT_EQ(wout1.phips, wout2.phips);
  EXPECT_EQ(wout1.over_r, wout2.over_r);
  EXPECT_EQ(wout1.jdotb, wout2.jdotb);
  EXPECT_EQ(wout1.bdotgradv, wout2.bdotgradv);
  EXPECT_EQ(wout1.DMerc, wout2.DMerc);
  EXPECT_EQ(wout1.DShear, wout2.DShear);
  EXPECT_EQ(wout1.DWell, wout2.DWell);
  EXPECT_EQ(wout1.DCurr, wout2.DCurr);
  EXPECT_EQ(wout1.DGeod, wout2.DGeod);
  EXPECT_EQ(wout1.equif, wout2.equif);
  EXPECT_EQ(wout1.curlabel, wout2.curlabel);
  EXPECT_EQ(wout1.potvac, wout2.potvac);
  EXPECT_EQ(wout1.xm, wout2.xm);
  EXPECT_EQ(wout1.xn, wout2.xn);
  EXPECT_EQ(wout1.xm_nyq, wout2.xm_nyq);
  EXPECT_EQ(wout1.xn_nyq, wout2.xn_nyq);
  EXPECT_EQ(wout1.raxis_cc, wout2.raxis_cc);
  EXPECT_EQ(wout1.zaxis_cs, wout2.zaxis_cs);
  EXPECT_EQ(wout1.rmnc, wout2.rmnc);
  EXPECT_EQ(wout1.zmns, wout2.zmns);
  EXPECT_EQ(wout1.lmns_full, wout2.lmns_full);
  EXPECT_EQ(wout1.lmns, wout2.lmns);
  EXPECT_EQ(wout1.gmnc, wout2.gmnc);
  EXPECT_EQ(wout1.bmnc, wout2.bmnc);
  EXPECT_EQ(wout1.bsubumnc, wout2.bsubumnc);
  EXPECT_EQ(wout1.bsubvmnc, wout2.bsubvmnc);
  EXPECT_EQ(wout1.bsubsmns, wout2.bsubsmns);
  EXPECT_EQ(wout1.bsubsmns_full, wout2.bsubsmns_full);
  EXPECT_EQ(wout1.bsupumnc, wout2.bsupumnc);
  EXPECT_EQ(wout1.bsupvmnc, wout2.bsupvmnc);
  EXPECT_EQ(wout1.raxis_cs, wout2.raxis_cs);
  EXPECT_EQ(wout1.zaxis_cc, wout2.zaxis_cc);
  EXPECT_EQ(wout1.rmns, wout2.rmns);
  EXPECT_EQ(wout1.zmnc, wout2.zmnc);
  EXPECT_EQ(wout1.lmnc_full, wout2.lmnc_full);
  EXPECT_EQ(wout1.lmnc, wout2.lmnc);
  EXPECT_EQ(wout1.gmns, wout2.gmns);
  EXPECT_EQ(wout1.bmns, wout2.bmns);
  EXPECT_EQ(wout1.bsubumns, wout2.bsubumns);
  EXPECT_EQ(wout1.bsubvmns, wout2.bsubvmns);
  EXPECT_EQ(wout1.bsubsmnc, wout2.bsubsmnc);
  EXPECT_EQ(wout1.bsubsmnc_full, wout2.bsubsmnc_full);
  EXPECT_EQ(wout1.bsupumns, wout2.bsupumns);
  EXPECT_EQ(wout1.bsupvmns, wout2.bsupvmns);
}

#endif  // VMECPP_VMEC_OUTPUT_QUANTITIES_TEST_HELPERS_H_"
